plugins {
    id("ca.coglinc.javacc") version "2.4.0"
}

sourceSets {
    create("base")
    create("generated")
}

val generated by sourceSets
val base by sourceSets

dependencies {
    "baseImplementation"(project(":jwasm"))
    implementation(project(":jwasm"))
    "generatedImplementation"(project(":jwasm"))

    "baseImplementation"(project(":jwasm-tree"))
    implementation(project(":jwasm-tree"))
    "generatedImplementation"(project(":jwasm-tree"))

    "generatedImplementation"(base.allSource)

    implementation(base.allSource)
    implementation(generated.allSource)
}

tasks.jar {
    from(generated.output, base.output, sourceSets.main.get().output)
}

tasks.compileJavacc {
    inputDirectory = file("src/main/javacc")
    outputDirectory = file("src/generated/java/io/github/eutro/jwasm/sexp/gen")
}
